name: RageQuit
main: io.github.Dinner1111.RageQuit.RageQuitPlugin
version: 1.1.0.7

commands:
  rq:
    description: Rage quit.
    usage: /rq
    permission: RageQuit.Rage
    permission: RageQuit.Rage.Console
    permission-message: Sorry, you can't rage quit.
